### ISSUE TITLE
Adding Temporal.(Calendar|TimeZone).prototype.equals

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1605] opened 2021-07-02 01:19 UTC
Somehow currently in the spec, we have  CalendarEquals Abstract Operation 
https://tc39.es/proposal-temporal/#sec-temporal-calendarequals
but there are no Temporal.Calendar.prototype.equals

I found it odd that we do not have a method for that. 

Also the same that we have
TimeZoneEquals defined  in https://tc39.es/proposal-temporal/#sec-temporal-timezoneequals
which is used by
6.3.40 Temporal.ZonedDateTime.prototype.equals ( other )

but there are no Temporal.TimeZone.prototype.equals in the spec.

@justingrant @ptomato @ryzokuken @sffc @Ms2ger

**Comment by ptomato** [comment] 2021-07-02 22:31
Duplicate of #1587

**Closed by ptomato** 2021-07-02 22:31 UTC
