### ISSUE TITLE
Should there be a `compatible` option for `DateTime.prototype.inTimeZone` disambiguation?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#614] opened 2020-05-22 22:05 UTC
From the [docs](https://tc39.es/proposal-temporal/docs/ambiguity.html): 

> Compatibility Note: The built-in behaviour of the Moment Timezone and Luxon libraries is to give the same result as `earlier` when turning the clock back, and `later` when setting the clock forward.

It's not just moment/luxon. They inherited this behavior from legacy `Date` which has the same behavior, thanks to this section in the [spec](https://www.ecma-international.org/ecma-262/#sec-local-time-zone-adjustment): 

> When `tlocal` represents local time repeating multiple times at a negative time zone transition (e.g. when the daylight saving time ends or the time zone adjustment is decreased due to a time zone rule change) or skipped local time at a positive time zone transitions (e.g. when the daylight saving time starts or the time zone adjustment is increased due to a time zone rule change), `tlocal` must be interpreted with the time zone adjustment before the transition.

Some developers may want to keep a Date-compatible behavior, and the workaround seems challenging. Here's the simplest workaround I could think of:
* call inTimeZone twice, once with `earlier` and again with `later`
* if they're same, then stop
* if they're different, then;
  *  subtract one day from the `earlier` result (`timeZone.prototype.getTransitions` can't iterate backwards, although #613 might prompt fixing this)
  * get that `Absolute`'s time zone offset
  * pick the `Absolute` matching that offset

This seems like a hassle and bad for performance.

Should there be a `compatible` option too?

**Comment by ptomato** [comment] 2020-05-22 22:14
I'd say this is a duplicate of #318, there's a pull request attached to that issue adding `TimeZone.getPossibleAbsolutesFor()` which should simplify this a lot.

The workaround would then become:
```js
function dateTimeInTimeZoneCompatible(dateTime, timeZone) {
  const possible = timeZone.getPossibleAbsolutesFor(dateTime);
  if (possible.length === 0) return timeZone.getAbsoluteFor(dateTime, { disambiguation: 'later' });
  return possible[0];
}
```

I wouldn't be opposed to adding `"compatible"` if that seemed to be a common use case, but let's move the discussion over to #318.

**Closed** 2020-05-22 22:14 UTC
