### ISSUE TITLE
Which built-in calendars (suggestion)

### ISSUE THREAD

**Issue by Louis-Aime** [tc39/proposal-temporal#1128] opened 2020-11-05 10:57 UTC
A built-in calendar generally provides a structure of names for the dates elements, and a reckoning system that enables conversion to and from ISO8601. I suppose that Temporal.Calendar essentially aims at enabling small variants like shifting by one or two days the Hijri calendar, setting an alternate origin to the gregorian calendar like `roc` or `buddhist`. 

May I then suggest to add the `julian` calendar to the list of built-in calendars. Although it is not officially used to today, it remains the reference calendar for many communities. The Julian calendar reckoning system is still used by other communities, e.g. [the Berbers](https://en.wikipedia.org/wiki/Berber_calendar).

With the julian calendar and the gregory, it is rather easy to create all kinds of western calendars, that differ by the date of switching to the Gregorian reckoning system. Today, there is no way to represent properly any historical date in Western Europe before 1582. They would be custom-made from built-in Julian and Gregorian.

Other candidates for built-in calendars are a very little number of _algorithmic_ calendars. They may be incorporated at any time.

- [French Republican calendar](https://en.wikipedia.org/wiki/French_Republican_calendar), although there are still discussions about the reckoning system. This calendar was the official calendar in France from late 1793 until 1806.
- [Maya](https://en.wikipedia.org/wiki/Maya_calendar)
- If I may, the [Milesian calendar](http://calendriermilesien.org/), for which the open source reckoning system and data for cldr are available.

**Comment by ptomato** [comment] 2020-11-06 18:11
Duplicate of #541 — you could advocate for adding more there, but my personal opinion is that environments ought to have neither more nor fewer built-in calendars than the ones already built-in to the `Intl` object. The Temporal specification itself describes only the `iso8601` calendar.

**Closed by ptomato** 2020-11-06 18:11 UTC
