### ISSUE TITLE
DifferenceTemporalPlainYearMonth: TemporalDurationFromInternal is infallible

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#3051] opened 2024-12-04 15:58 UTC
Step 17:
> Let result be ? TemporalDurationFromInternal(duration, day).

`TemporalDurationFromInternal` should be infallible in this context.

**Comment by ptomato** [comment] 2024-12-04 20:24
Duplicate of #3025 - sorry I didn't get around to that one yet.

**Closed by ptomato** 2024-12-04 20:24 UTC
