### ISSUE TITLE
To align to IETF feedback, update offset string serialization/deserialization to hide sub-minute offsets 

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1793] opened 2021-08-31 18:04 UTC
Our discussion with IETF yielded a normative change described below. It was mentioned briefly in the 2021-08-31 plenary session and will be submitted for approval in the Oct 2021 meeting. The bold parts below are the changes needed. 

From https://github.com/tc39/proposal-temporal/blob/main/meetings/agenda-minutes-2021-06-10.md#ietf-update:

- PFC: https://github.com/tc39/proposal-temporal/issues/935#issuecomment-703018002 is the decision that we are revisiting now, with good reason: our nanoseconds extension is not going to get standardized. I would recommend that we leave the `ZonedDateTime.offset` property as-is and only make this change to the ISO string serialization and deserialization, because JGT gave good reasons in that discussion for `ZonedDateTime.offset` to be the way it is.
- Consensus:
  - **Change `ZonedDateTime.toString()` and `Instant.toString()` to output time zone offsets only with minutes precision.**
  - **Change `ZonedDateTime.from()` to accept `HH:MM` precision for non-minute-offset time zones, even with `offset: 'reject'`.**
  - **No change to `ZonedDateTime.offset` property, `offset` property in property bags, and `TimeZone.getOffsetStringFor()`.**
- RGN: I see that ISO 8601-2 does allow a seconds timezone offset, but those are the extensions that aren't generally supported anywhere, even in Temporal.
- USA: My issue with ISO 8601-2 is that it's a mixed bag, there are things that make sense and things that don't.

**Comment by ptomato** [comment] 2021-09-16 23:00
I think this is a duplicate of #1544. I'll combine them.

**Closed by ptomato** 2021-09-16 23:00 UTC
